# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# App server (VM1: 195.47.196.46)
host    enb_DB          enb_app         195.47.196.46/32        scram-sha-256

# Deny everything else
host    all             all             0.0.0.0/0               reject
