# Generated by Django 5.1.15 on 2026-03-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Advert',
                    fields=[
                        (
                            'id',
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'advert',
                        'managed': False,
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='AdvertPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='adverts/photos/')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='legacy.advert')),
            ],
            options={
                'db_table': 'advert_photo',
                'indexes': [models.Index(fields=['advert', 'sort'], name='advert_phot_advert__6dd1c1_idx')],
            },
        ),
    ]
