# Generated by Django 5.1.15 on 2026-03-11 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_advert_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('sort', models.IntegerField(default=0)),
                ('active', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('active', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('username', models.CharField(max_length=255, unique=True)),
                ('auth_key', models.CharField(max_length=32)),
                ('password_hash', models.CharField(max_length=255)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('contacts', models.TextField()),
            ],
            options={
                'db_table': 'legacy_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('object_id', models.PositiveIntegerField(db_column='object')),
                ('points', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('contacts', models.JSONField()),
                ('price_list', models.PositiveIntegerField()),
                ('links', models.TextField()),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'seller',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='advertphoto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
