# Generated by Django 5.1.15 on 2026-03-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_catalog_categories_file_legacyuser_migration_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('advert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='legacy.advert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='legacy.legacyuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='legacy.legacyuser')),
            ],
            options={
                'db_table': 'message',
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='message_recipie_2b2000_idx'), models.Index(fields=['sender', '-created_at'], name='message_sender__adf9a6_idx')],
            },
        ),
    ]
