# Generated by Django 6.0.3 on 2026-04-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0015_extra_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('vk', 'ВКонтакте'), ('ok', 'Одноклассники')], max_length=10)),
                ('provider_uid', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, default='', max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_account',
            },
        ),
        migrations.RenameIndex(
            model_name='advertview',
            new_name='advert_view_advert__28bae4_idx',
            old_name='advert_view_advert_created_idx',
        ),
        migrations.RenameIndex(
            model_name='advertview',
            new_name='advert_view_advert__db00ca_idx',
            old_name='advert_view_advert_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='favorite_user_id_7b4a12_idx',
            old_name='favorite_user_id_created_idx',
        ),
        migrations.AlterField(
            model_name='advertview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='legacy.legacyuser'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user'], name='social_acco_user_id_edb1fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'provider_uid')},
        ),
    ]
