# Generated by Django 6.0.3 on 2026-04-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0016_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('vkid', 'VK ID')], max_length=10),
        ),
    ]
