# Generated by Django 6.0.3 on 2026-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0017_unified_vkid_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отписка от рассылки',
                'verbose_name_plural': 'Отписки от рассылки',
                'db_table': 'email_unsubscribe',
            },
        ),
    ]
