# Generated by Django 5.1.15 on 2026-06-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_fields', '0003_free_plan_drop_area_cap'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fieldevent',
            new_name='myf_field_e_field_i_c8b9e4_idx',
            old_name='myf_event_field_d_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldevent',
            new_name='myf_field_e_season__179ff4_idx',
            old_name='myf_event_season_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldevent',
            new_name='myf_field_e_event_t_e05651_idx',
            old_name='myf_event_type_d_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldphoto',
            new_name='myf_field_p_field_i_3373e5_idx',
            old_name='myf_photo_field_t_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldphoto',
            new_name='myf_field_p_event_i_dfea29_idx',
            old_name='myf_photo_event_idx',
        ),
        migrations.RenameIndex(
            model_name='userfield',
            new_name='myf_field_owner_i_59a587_idx',
            old_name='myf_field_owner_i_idx',
        ),
        migrations.RenameIndex(
            model_name='userfield',
            new_name='myf_field_region__446634_idx',
            old_name='myf_field_region_c_idx',
        ),
    ]
