# Generated by Django 6.0.3 on 2026-08-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_fields', '0004_rename_myf_event_field_d_idx_myf_field_e_field_i_c8b9e4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GisLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название слоя')),
                ('table_name', models.CharField(help_text='Физическая таблица со всеми объектами слоя (identifier ≤ 63 симв.).', max_length=63, unique=True, verbose_name='Таблица PostGIS')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Имя .shp')),
                ('source_archive', models.CharField(blank=True, default='', max_length=255, verbose_name='Исходный ZIP')),
                ('geom_kind', models.CharField(choices=[('point', 'Точки'), ('line', 'Линии'), ('polygon', 'Полигоны'), ('other', 'Прочее')], default='other', max_length=10, verbose_name='Тип геометрии')),
                ('geom_type', models.CharField(blank=True, default='', help_text='Напр. Polygon / MultiPolygon / Point.', max_length=40, verbose_name='OGR geom type')),
                ('srid_original', models.IntegerField(default=0, help_text='0 — проекция не определена (.prj отсутствует), принята как 4326.', verbose_name='Исходный SRID')),
                ('feature_count', models.IntegerField(default=0, verbose_name='Объектов')),
                ('attributes', models.JSONField(blank=True, default=list, verbose_name='Атрибуты')),
                ('extent', models.JSONField(blank=True, null=True, verbose_name='Охват (4326)')),
                ('color', models.CharField(default='#e91e63', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gis_layers', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'ГИС-слой (SHP)',
                'verbose_name_plural': 'ГИС-слои (SHP)',
                'db_table': 'myf_gis_layer',
                'ordering': ['-created_at'],
            },
        ),
    ]
