# Generated by Django 6.0.3 on 2026-08-26 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_fields', '0008_gisfolder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название слоя')),
                ('status', models.CharField(choices=[('uploading', 'Загрузка'), ('queued', 'В очереди'), ('processing', 'Обработка'), ('ready', 'Готов'), ('failed', 'Ошибка')], db_index=True, default='uploading', max_length=12, verbose_name='Статус')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('upload_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Ключ оригинала (S3)')),
                ('cog_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Ключ COG (S3)')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Размер, байт')),
                ('srid', models.IntegerField(default=0, help_text='EPSG исходного растра (0 — не определён).', verbose_name='SRID')),
                ('bounds', models.JSONField(blank=True, null=True, verbose_name='Охват (4326)')),
                ('band_count', models.IntegerField(default=0, verbose_name='Каналов')),
                ('nodata', models.FloatField(blank=True, null=True, verbose_name='NoData')),
                ('stats', models.JSONField(blank=True, default=list, verbose_name='Статистика каналов')),
                ('style', models.JSONField(blank=True, default=dict, verbose_name='Стиль')),
                ('opacity', models.FloatField(default=1.0, verbose_name='Непрозрачность')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('sort_order', models.IntegerField(default=0, help_text='Меньше — выше в списке слоёв и на карте.', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raster_layers', to='my_fields.gisfolder', verbose_name='Папка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raster_layers', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Растровый слой',
                'verbose_name_plural': 'Растровые слои',
                'db_table': 'myf_raster_layer',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
