# Generated by Django 6.0.3 on 2026-04-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0008_rename_indexes_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdviBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_year', models.SmallIntegerField(verbose_name='День года (1‑366)')),
                ('mean_ndvi', models.FloatField(verbose_name='Среднее NDVI')),
                ('years_count', models.SmallIntegerField(default=0, verbose_name='Кол-во лет')),
                ('crop_type', models.CharField(blank=True, choices=[('arable', 'Пашня'), ('hayfield', 'Сенокос'), ('pasture', 'Пастбище'), ('perennial', 'Многолетнее насаждение'), ('other', 'Прочее')], default='', max_length=20, verbose_name='Вид угодья (пусто = все)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_baselines', to='agrocosmos.district')),
            ],
            options={
                'verbose_name': 'Базовая линия NDVI',
                'verbose_name_plural': 'Базовые линии NDVI',
                'db_table': 'agro_ndvi_baseline',
                'indexes': [models.Index(fields=['district', 'crop_type', 'day_of_year'], name='agro_ndvi_b_distric_72cc35_idx')],
                'unique_together': {('district', 'day_of_year', 'crop_type')},
            },
        ),
    ]
