# Generated by Django 6.0.3 on 2026-04-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0009_ndvi_baseline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='task_type',
            field=models.CharField(choices=[('upload_region', 'Загрузка региона'), ('upload_farmlands', 'Загрузка угодий'), ('archive_ndvi', 'Архивные данные NDVI (MODIS)'), ('raster_ndvi', 'Растровые данные NDVI (S2/L8)'), ('monitoring', 'Мониторинг NDVI')], max_length=30, verbose_name='Тип процесса'),
        ),
    ]
