# Generated by Django 6.0.3 on 2026-04-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0010_add_raster_ndvi_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationindex',
            name='is_anomaly',
            field=models.BooleanField(default=False, verbose_name='Аномалия (выброс)'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='mean_smooth',
            field=models.FloatField(blank=True, null=True, verbose_name='NDVI сглаженное'),
        ),
    ]
