# Generated by Django 6.0.3 on 2026-04-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0011_add_anomaly_and_smooth_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmlandPhenology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('source', models.CharField(choices=[('modis', 'MODIS'), ('raster', 'S2/L8')], default='modis', max_length=10, verbose_name='Источник')),
                ('sos_date', models.DateField(blank=True, null=True, verbose_name='Начало сезона (SOS)')),
                ('eos_date', models.DateField(blank=True, null=True, verbose_name='Конец сезона (EOS)')),
                ('pos_date', models.DateField(blank=True, null=True, verbose_name='Пик сезона (POS)')),
                ('max_ndvi', models.FloatField(blank=True, null=True, verbose_name='Макс. NDVI')),
                ('los_days', models.IntegerField(blank=True, null=True, verbose_name='Длит. сезона (дней)')),
                ('total_ndvi', models.FloatField(blank=True, null=True, verbose_name='Интеграл NDVI (TI)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenology', to='agrocosmos.farmland')),
            ],
            options={
                'verbose_name': 'Фенология угодья',
                'verbose_name_plural': 'Фенология угодий',
                'db_table': 'agro_farmland_phenology',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['farmland', 'year'], name='agro_farmla_farmlan_bc24fb_idx')],
                'unique_together': {('farmland', 'year', 'source')},
            },
        ),
    ]
