# Generated by Django 6.0.3 on 2026-04-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0012_add_farmland_phenology'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndvibaseline',
            name='std_ndvi',
            field=models.FloatField(default=0, verbose_name='Ст. отклонение NDVI'),
        ),
    ]
