# Generated by Django 6.0.3 on 2026-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0013_add_std_ndvi_to_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmlandphenology',
            name='mean_ndvi',
            field=models.FloatField(blank=True, null=True, verbose_name='Средн. NDVI за сезон'),
        ),
    ]
