# Generated by Django 5.1.15 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0032_yield_forecast_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='yieldfeatures',
            new_name='agro_yield__region__fcf467_idx',
            old_name='agro_yield__region__be041d_idx',
        ),
        migrations.RenameIndex(
            model_name='yieldfeatures',
            new_name='agro_yield__distric_387edc_idx',
            old_name='agro_yield__distric_2c9d68_idx',
        ),
        migrations.AlterField(
            model_name='cropyieldstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='districtndviseries',
            name='crop_type',
            field=models.CharField(choices=[('arable', 'Пашня'), ('fallow', 'Залежь'), ('hayfield', 'Сенокос'), ('pasture', 'Пастбище'), ('perennial', 'Многолетние насаждения'), ('other_agri', 'Иные с.-х. земли'), ('other', 'Прочее')], max_length=20, verbose_name='Тип угодья'),
        ),
        # NOTE: districtndviseries.id -> BigAutoField is intentionally NOT here.
        # That table has ~1.17M rows; int4->int8 rewrites it under an ACCESS
        # EXCLUSIVE lock. It lives in its own migration (0034) so this one stays
        # instant and auto-deploy-safe. See 0034 for the heavy conversion.
        migrations.AlterField(
            model_name='vegetationalert',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('arable', 'Пашня'), ('fallow', 'Залежь'), ('hayfield', 'Сенокос'), ('pasture', 'Пастбище'), ('perennial', 'Многолетние насаждения'), ('other_agri', 'Иные с.-х. земли'), ('other', 'Прочее')], default='', help_text='Для district-level алертов: культура, по которой сработал детектор.', max_length=20, verbose_name='Тип угодья'),
        ),
        migrations.AlterField(
            model_name='yieldfeatures',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yieldforecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='yieldforecastmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
