# Generated by Django 6.0.3 on 2026-08-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0034_districtndviseries_id_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationindex',
            name='histogram',
            field=models.JSONField(blank=True, null=True, verbose_name='Гистограмма NDVI (5 бинов)'),
        ),
    ]
