# Generated by Django 6.0.3 on 2026-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0035_vegetationindex_histogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='task_type',
            field=models.CharField(choices=[('upload_region', 'Загрузка региона'), ('upload_districts', 'Загрузка районов'), ('upload_farmlands', 'Загрузка угодий'), ('archive_ndvi', 'Архивные данные NDVI (MODIS)'), ('raster_ndvi', 'Растровые данные NDVI (S2/L8)'), ('monitoring', 'Мониторинг NDVI'), ('gis_overlay', 'Оверлей ГИС-слоёв')], max_length=30, verbose_name='Тип процесса'),
        ),
    ]
