# Generated by Django 6.0.3 on 2026-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocosmos', '0040_farmlandcropseason_harvest_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmlandcropseason',
            name='is_harvested',
            field=models.BooleanField(default=False, help_text='Есть уборочный спад NDVI после пика (пашня/сенокос).', verbose_name='Угодье убрано'),
        ),
        migrations.AlterField(
            model_name='farmlandcropseason',
            name='season_class',
            field=models.CharField(choices=[('winter', 'Озимые'), ('spring', 'Яровые'), ('hayfield', 'Сенокос'), ('unused', 'Не обрабатывается'), ('unknown', 'Не определено')], default='unknown', max_length=10, verbose_name='Класс сезона'),
        ),
    ]
