# Generated by Django 6.0.3 on 2026-08-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy', '0018_email_unsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('gis_layer', 'ГИС-слой (SHP)')], default='gis_layer', max_length=20, verbose_name='Тип ресурса')),
                ('resource_id', models.IntegerField(blank=True, help_text='Пусто = доступ ко ВСЕМ ресурсам этого типа.', null=True, verbose_name='ID ресурса')),
                ('level', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование'), ('manage', 'Управление (в т.ч. удаление)')], default='view', max_length=10, verbose_name='Уровень доступа')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, db_column='granted_by_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legacy.legacyuser', verbose_name='Кем выдан')),
                ('legacy_user', models.ForeignKey(db_column='legacy_user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_grants', to='legacy.legacyuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Грант доступа',
                'verbose_name_plural': 'Гранты доступа',
                'db_table': 'access_resource_grant',
                'ordering': ['legacy_user_id', 'resource_type', 'resource_id'],
                'indexes': [models.Index(fields=['legacy_user', 'resource_type'], name='access_reso_legacy__215769_idx')],
                'unique_together': {('legacy_user', 'resource_type', 'resource_id')},
            },
        ),
    ]
