# Generated by Django 6.0.3 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegrant',
            name='resource_type',
            field=models.CharField(choices=[('gis_layer', 'ГИС-слой (SHP)'), ('raster_layer', 'Растровый слой (GeoTIFF/COG)')], default='gis_layer', max_length=20, verbose_name='Тип ресурса'),
        ),
    ]
